# -*- coding: utf-8 -*-
"""dependencied\s for brok

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wo-C6yQMWs6sSHJgnW10NHQPddW1PQC1
"""

torch
transformers
accelerate
bitsandbytes